version: '2'

services:
  dashboard:
    image: sayhi/dashboard
    ports:
      - "4000:4000"
  server:
    image: sayhi/server
    ports:
      - "8080:8080"
  nginx:
      build: sayhi/sayhi-nginx
      ports:
          - "80:80"
