version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./certs:/etc/nginx/certs:ro"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/etc/nginx/certs:rw"

  dashboard:
    image: sayhi/dashboard
    container_name: dashboard
    restart: always
    environment:
      - VIRTUAL_HOST=${DASHBOARD_DOMAIN}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DASHBOARD_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}

  server:
    image: sayhi/server
    restart: always
    container_name: server
    environment:
      - VIRTUAL_HOST=${SERVER_DOMAIN}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${SERVER_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}

  page:
    image: sayhi/landing-page
    restart: always
    container_name: landing-page
    environment:
      - VIRTUAL_HOST=${PAGE_DOMAIN}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${PAGE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}
