version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  dashboard:
    image: sayhi/dashboard
    restart: always
    environment:
      - VIRTUAL_HOST=dashboard.localhost
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}

  server:
    image: sayhi/server
    restart: always
    environment:
      - VIRTUAL_HOST=server.localhost
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}

  page:
    image: sayhi/landing-page
    restart: always
    environment:
      - VIRTUAL_HOST=localhost
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}

  watchtower:
    image: centurylink/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
