version: "2"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "../../../volumes/proxy/certs:/etc/nginx/certs:ro"
    networks:
      - proxy-tier

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "../../../volumes/proxy/templates/nginx-compose-v2.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../../../volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  dashboard:
    image: sayhi/dashboard
    restart: always
    container_name: dashboard
    volumes:
      - "../../../volumes/examples/simple-site/conf.d/:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=${DASHBOARD}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DASHBOARD}
      - LETSENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}
    networks:
      - proxy-tier

  server:
    image: sayhi/server
    restart: always
    container_name: server
    volumes:
      - "../../../volumes/examples/simple-site/conf.d/:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=${SERVER}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${SERVER}
      - LETSENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}
    networks:
      - proxy-tier

  page:
    image: sayhi/landing-page
    restart: always
    container_name: landing-page
    volumes:
      - "../../../volumes/examples/simple-site/conf.d/:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=${PAGE}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${PAGE}
      - LETSENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy