version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./redirect.conf:/etc/nginx/conf.d/redirect.conf:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./certs:/etc/nginx/certs:ro"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/etc/nginx/certs:rw"

  server:
    image: exemplator/exemplator
    restart: always
    container_name: server
    environment:
      - VIRTUAL_HOST=${SERVER_DOMAIN}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${SERVER_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}

  page:
    image: exemplator/exemplator-page
    restart: always
    container_name: page
    environment:
      - VIRTUAL_HOST=www.${PAGE_DOMAIN},${PAGE_DOMAIN}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${PAGE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - SERVER_URL=${SERVER}
      - DASHBOARD_URL=${DASHBOARD}
      - PAGE_URL=${PAGE}

  watchtower:
    image: centurylink/watchtower
    restart: always
    container_name: watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"